server:
  port: 7000
logging:
  file: 
    path: C:/elk/vz_profile_service
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.verizon.profile: DEBUG
  pattern:
    level: "%d %-5level [%thread] %logger : %msg%n"
spring:
  application:
    name: serviceProfile
  profiles:
    active:
    - dev
  cloud:
    config:
      uri:
      - http://localhost:8888/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost